# hpa
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "${APP_NAME}-autoscaler"
spec:
  maxReplicas: ${MAXREPLICAS}
  minReplicas: ${MINREPLICAS}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "${APP_NAME}"
  targetCPUUtilizationPercentage: 50